# **08장 연습문제**

1번

In [ ]:
import matplotlib.pyplot as plt

year = [2006, 2009, 2012, 2015, 2018]
kor = [547, 546, 554, 524, 526]
#선그래프
#그래프 출력

In [ ]:
import matplotlib.pyplot as plt

year = ['2006', '2009', '2012', '2015', '2018']
kor = [547, 546, 554, 524, 526]
#막대그래프
plt.show()

In [ ]:
import matplotlib.pyplot as plt

kor = [547, 546, 554, 524, 526]
usa = [474, 487, 481, 470, 478]
#산점도그래프
plt.show()

In [ ]:
import matplotlib.pyplot as plt

score = [547,546,554,524,526,474,487,481,470,478,523,529,536,532,527]
#히스토그램
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = [2009, 2012, 2015]
y = [529, 536, 532]
plt.plot(x, y)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = [2006, 2009, 2012, 2015]
y = [523, 529, 536, 532]
plt.plot(x, y)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = ['a', 'b', 'c']
y = [7, 5, 4]
plt.bar(x, y)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

year = [2006, 2009, 2012, 2015, 2018]
kor = [547, 546, 554, 524, 526]
plt.plot(year, kor)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

year = [2006, 2009, 2012, 2015, 2018]
kor = [547, 546, 554, 524, 526]
usa = [474, 487, 481, 470, 478]
# year kor 그래프
# year usa 그래프
plt.show()

In [ ]:
import matplotlib.pyplot as plt

year = [2006, 2009, 2012, 2015, 2018]
kor = [547, 546, 554, 524, 526]
usa = [474, 487, 481, 470, 478]
jpn = [523, 529, 536, 532, 527]

# 그래프가 가로와 세로 크기를 각각 5인치와 3인치 크기 설정
# year 데이터를 x축으로, kor 데이터를 y축으로 하여 빨간색 점선으로 선 그래프를 그리고 범례에 'Korea'라고 표시
plt.plot(year, usa, 'b:', ) #범례에 'Korea'라고 표시
plt.plot(year, jpn, 'g-', label='Japan')
plt.ylim(400, 600)  # y축 범위 설정
# 그래프에 범례를 추가
# 그래프 제목을 'Mathematics performance'로 설정합니다.
plt.xlabel('year')
plt.ylabel('score')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

notebook = {'g○○':150,'t○○':100,'m○○':160,'s○○':170}

plt.figure(figsize=(5,3))
# 막대 그래프의 x축은 딕셔너리의 키(제품이름)를 사용하고, 막대 그래프의 Y축은 딕셔너리의 값(가격)을 사용하고, 각 막대의 너비를 0.7 단위로 설정
plt.xlabel('product name')
plt.ylabel('price')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

year = [2000, 2005, 2010, 2015, 2020]
single_person = [15.5, 20.0, 23.9, 27.2, 31.7]
baby_born = [640089, 438707, 470171, 438420, 272337]

plt.figure(figsize=(5,3))
 # 1인 가구 비율(single_person)과 출생아 수(baby_born) 사이의 관계를 나타내는 산점도를 그립니다.
for i in range(len(year)):
  plt.annotate(year[i],xy=(single_person[i], baby_born[i]),xytext=(5,-10),textcoords='offset points') #각 연도에 해당하는 데이터 지점 옆에 해당 연도를 표시하는 주석을 추가
plt.xlim(14,35)
plt.ylim(230000,700000)
plt.xlabel('single-person household ratio')
plt.ylabel('the number of babies born')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import random

x = [random.randint(1,100) for i in range(1000)]

plt.figure(figsize=(5,3))
# 데이터 배열 x를 20개의 구간으로 나누고 50% 투명도로 표시하는 빈도 분포 그래프를 생성
plt.ylabel('frequency')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

exercise ={'climbing':0,'soccer':0,'swimming':0,'tennis':0}

print('좋아하는 운동을 입력하세요.')
print('복수 개의 운동을 입력하려면 콤마로 구분하세요.')

while True:
  s = input('climbing,soccer,swimming,tennis,종료: ')
  if s=='종료':
    break
  for a in s.split(','):
    if a in exercise:
      # 해당 운동의 카운트를 1 증가시키는 연산
    else:
      print(f'{a}는 등록되지 않은 운동입니다.')

plt.figure(figsize=(5.5,3))
plt.bar(exercise.keys(), exercise.values(), color='g', width=0.6)
#plt.xticks(rotation='vertical')
plt.xlabel('exercise')
plt.ylabel('frequency')
plt.show()

In [ ]:
#e데이터포인트에 값표시하는법
#데이터는 월별강수량 데이터,
#i에 값을 계속 넣어서, text라는 메서드 사용
#x는 인덱스값(i), y=value+10으로 왜? y좌표값을 데이터포인트 위로 두어서 가독성 증가

#시각화를 위한 데이터는 문자형이어야 plt.text사용가능
#그래서value값을 str(value)형식으로하는거, ha, va는 위치 중앙정렬, 하위정렬

plt.figure(figsize=(12,6))
for i value in enumerate(rainfall):
  plt.text(i, value+ 10, str(value), ha='center', va='bottom)')

In [4]:
#numpy
#리스트=배열
#pip install numpy
import numpy as np

a = np.array([1, 2, 3])
print(a)
b = np.array([[1, 2], [3, 4]])
print(b)
type(a)
print(np.zeros((2, 3))) #0으로 이뤄진 2차원배열
print(np.ones(5))            # 길이 5의 1 배열
print(np.arange(0, 10, 2))   # 0부터 10까지 2씩 증가
print(np.linspace(0, 1, 5))  # 0~1 사이를 5개로 나눈 배열
print(np.random.rand(3))     # 0~1 사이의 난수 3개
#첫번째괄호가 행, 2행 3열이면 [1,2,3], [4,5,6]이런식일것

#2차원배열인덱싱? 특저위치의 값을 수정 접근하는 법
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print(matrix[0, 1])      # 첫 번째 행, 두 번째 열
print(matrix[1:])        # 두 번째 행 이후 모두

#조건부선택
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])  # 30보다 큰 요소만


[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#1차원 배열, 5개의 요소, 0으로 초기화된 배열
#1줄,
arr = np.zeros(5)


array([0., 0., 0., 0., 0.])

 문제 2: 1부터 10까지의 숫자 중 짝수만 포함하는 배열을 생성하세요.
📝 문제 3: [2, 4, 6] 배열과 [10, 20, 30] 배열을 각각 생성하고, 곱셈 연산을 수행한 결과를 출력하세요.
📝 문제 4: 위 배열에서 20보다 큰 요소만 필터링해서 출력하세요.


In [11]:
#2
a = np.arange(2, 11, 2)
print(a)

[ 2  4  6  8 10]


In [14]:
#3
a = np.array([2,4,6])
b= np.array([10,20,30])
result = a*b
print(result)
#4
print(result[result>20])

[ 20  80 180]
[ 80 180]


In [23]:

import pandas as pd
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
df.tail()

이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여

In [27]:
df= pd.read_csv('tested.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [31]:
df[df['Age']>25]

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
6            898         1       3   
..           ...       ...     ...   
407         1299         0       1   
411         1303         1       1   
412         1304         1       3   
414         1306         1       1   
415         1307         0       3   

                                                Name     Sex   Age  SibSp  \
0                                   Kelly, Mr. James    male  34.5      0   
1                   Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2                          Myles, Mr. Thomas Francis    male  62.0      0   
3                                   Wirz, Mr. Albert    male  27.0      0   
6                               Connolly, Miss. Kate  female  30.0      0   
..                                               ...     ...   ...    ...   
407                       Widener, Mr. George Dunton    male  50.0      1   
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
412                   Henriksson, Miss. Jenny Lovisa  female  28.0      0   
414                     Oliva y Ocana, Dona. Fermina  female  39.0      0   
415                     Saether, Mr. Simon Sivertsen    male  38.5      0   

     Parch              Ticket      Fare Cabin Embarked  
0        0              330911    7.8292   NaN        Q  
1        0              363272    7.0000   NaN        S  
2        0              240276    9.6875   NaN        Q  
3        0              315154    8.6625   NaN        S  
6        0              330972    7.6292   NaN        Q  
..     ...                 ...       ...   ...      ...  
407      1              113503  211.5000   C80        C  
411      0               19928   90.0000   C78        Q  
412      0              347086    7.7750   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  

[190 rows x 12 columns]

In [40]:
df.dropna(axis=0, inplace=True) # Change 0 to axis=0
df

PassengerId  Survived  Pclass  \
12           904         1       1   
14           906         1       1   
24           916         1       1   
26           918         1       1   
28           920         0       1   
..           ...       ...     ...   
404         1296         0       1   
405         1297         0       2   
407         1299         0       1   
411         1303         1       1   
414         1306         1       1   

                                                  Name     Sex   Age  SibSp  \
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1   
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
24     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  female  48.0      1   
26                        Ostby, Miss. Helene Ragnhild  female  22.0      0   
28                             Brady, Mr. John Bertram    male  41.0      0   
..                                                 ...     ...   ...    ...   
404                       Frauenthal, Mr. Isaac Gerald    male  43.0      1   
405       Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0   
407                         Widener, Mr. George Dunton    male  50.0      1   
411    Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1   
414                       Oliva y Ocana, Dona. Fermina  female  39.0      0   

     Parch         Ticket      Fare            Cabin Embarked  
12       0          21228   82.2667              B45        S  
14       0    W.E.P. 5734   61.1750              E31        S  
24       3       PC 17608  262.3750  B57 B59 B63 B66        C  
26       1         113509   61.9792              B36        C  
28       0         113054   30.5000              A21        S  
..     ...            ...       ...              ...      ...  
404      0          17765   27.7208              D40        C  
405      0  SC/PARIS 2166   13.8625              D38        C  
407      1         113503  211.5000              C80        C  
411      0          19928   90.0000              C78        Q  
414      0       PC 17758  108.9000             C105        C  

[87 rows x 12 columns]

In [43]:
#df.groupby('그룹화할 열')[대상 열].집계함수()
#그룹화의 기준으로 대상열을 정리
df.groupby('Sex')['Age'].mean()

Sex
female    39.590909
male      38.895349
Name: Age, dtype: float64